name: face_security
description: Face Security Flutter Project

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^0.21.0
  bloc: ^0.15.0
  firebase_messaging: ^5.1.6
  meta: ^1.1.7
  equatable: ^0.6.1
  moor_flutter: ^2.0.0
  retrofit: ^1.0.1
  dio: ^3.0.3
  image_picker: ^0.6.1+4
  flutter_i18n: ^0.7.0
  get_it: ^3.0.1
  json_annotation: ^3.0.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^2.0.0
  retrofit_generator: ^1.0.1+1
  build_runner: ^1.7.1
  json_serializable: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/langs/
    - assets/images/